---
apiVersion: v1
kind: Secret
metadata:
  name: mailinabox
data:
  MAILINABOX_PASSWORD: MTIzNDU2
  MAILINABOX_URL: aHR0cHM6Ly9ib3gueW91cmRvbWFpbi5jb20vYWRtaW4vZG5zL2N1c3RvbS8=
  MAILINABOX_USER: eW91cmFkbWluQHlvdXJkb21haW4uY29t
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: mailinabox
  name: mailinabox
spec:
  ports:
  - name: "8080"
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: mailinabox
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mailinabox
  name: mailinabox
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mailinabox
  strategy: 
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: mailinabox
    spec:
      containers:
      - image: kbudde/mailinabox-dnsapi:v0
        name: mailinabox
        ports:
        - containerPort: 8080
        envFrom:
          - secretRef:
              name: mailinabox
        resources: 
          limits:
            cpu: "50m"
            memory: "10Mi"
          requests:
            cpu: "50m"
            memory: "10Mi"

