name: Docker Build/Publish Image

on:
  schedule:
    - cron: '0 10 * * *' # everyday at 10am
  push:
    branches:
      - '**'
    tags:
      - 'v*.*.*'
  pull_request:

  workflow_dispatch:

env:
  PLATFORMS: linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - 
        name: Checkout the code
        uses: actions/checkout@v2.3.4
      -
        name: Docker meta
        id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v3.1.0
        with:
          images: kbudde/mailinabox-dnsapi
          tag-sha: true # add git short SHA as Docker tag
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1.2.0
      - 
        name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v1.3.0
      -
        name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1.9.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Declare some variables  
        id: vars
        shell: bash
        run: |
          echo "##[set-output name=branch;]$(echo ${GITHUB_REF}|grep -oP 'refs/heads/\K.*')"
          echo "::set-output name=version::$(echo ${GITHUB_REF}|grep -oP 'refs/tags/\K.*')"
          echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
      - 
        name: Build and push images
        uses: docker/build-push-action@v2.4.0
        with:
          platforms: ${{ env.PLATFORMS }}
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
          build-args: |
            VERSION=${{ steps.vars.outputs.version }}
            BRANCH=${{ steps.vars.outputs.branch }}
            COMMIT=${{ steps.vars.outputs.sha_short }}




